### ISSUE TITLE
Application stuck on vibrating, no input from controller

### ISSUE THREAD

**Issue by GMP67** [mfosse/JoyCon-Driver#25]
While running precompiled version of the app, it gets stuck on vibrating the JoyCon, console output below.
```
vJoy device 1 is free
Acquired device number 1 - OK
vJoy device 2 is free
Acquired device number 2 - OK
Found joycon R 0: 98b6e94ca6de \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vi
d&0002057e_pid&2007#9&86fa39&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
Enabling vibration...
Enabling IMU data...
Increase data rate for Bluetooth...
Successfully initialized Joy-Con (R)!
setting LEDs...
LEDs should be set.
vibrating JoyCon(s).
```

**Comment by GMP67** [comment]
This issue applies only to the most recent commit.

**Comment by mfosse** [comment]
yeah I was doing some testing and forgot to comment something out, it's fixed now.

**Comment by amithacoon** [comment]
i still have this problem, they start t and wont stop, im using an non original  joycons is that the problem? any way i could turn off the Vibration in init?
